finished the milestone2 of the 3rd week project Newsweek. Added the Featured stories,  Sponsored insights / Rankings, Top story, My turn,  Culture & travel, More stories, Latest news,  The debate, Opinion, Sponsored insights / Rankings, Free signup
igorkol91/NewsweekProject pull request #5
Opened 2021-04-06 20:42 UTC by igorkol91

2021-04-06 21:24 UTC, igorkol91 commented
We have worked on the second milestone for the "Newsweek" project;
We build the first part of the main section divided into 3 columns. It works on 3 different screen widths.
Kindly review our code.
Note: We tried to use as much bootstrap as possible for this project and only used CSS when we couldn't accomplish it with Bootstrap.
Thanks

2021-04-07 00:59 UTC, jcy2704 requested changes
<h1 align="center">CHANGES REQUIRED 👀🤔</h1>

## Hey @igorkol91 @ahzia!! You've done a really great job! 🙌

> **REMINDER: THIS IS THE FIRST REVIEW. YOU'LL HAVE TWO (2) MORE REVIEWS. IF YOU DON'T SUCCEED TO PASS BY THE THIRD REVIEW YOU'LL BE ASKED TO REPEAT THE SAME PROJECT THE NEXT WEEK. PLEASE MAKE SURE TO CHANGE WHAT IS ASKED FOR AND FIX EVERYTHING IF IT BREAKS IN ANY POINT BEFORE YOU ASK FOR A NEW REVIEW.**

### You've done really great using the Bootstrap classes and it looks very similar to the original, I like that. However, there are some changes I want to request.

- **I know you've really worked hard, but there are still many parts of the CSS that can be implemented with Bootstrap. This project requires you to use Bootstrap classes when possible.**
  
  -  [ ] Things like `text-align: center`, `display: inline-flex`, `margin: auto`, and many other similar attributes can be achieved using Bootstrap. I would like you to look at the documentation and on the internet for the classes. 

- **There are still minor things I need you to fix for the mobile resolution (320px).**

<img width="260" alt="image" src="https://user-images.githubusercontent.com/64392568/113795168-dfce2780-9711-11eb-854f-6acc44094264.png">

 - [ ] Center logo and align correctly the subscribe section

<img width="260" alt="image" src="https://user-images.githubusercontent.com/64392568/113795189-eceb1680-9711-11eb-87e8-8934c0013190.png">

- [ ] Images are not sized correctly

<img width="260" alt="image" src="https://user-images.githubusercontent.com/64392568/113795224-fd9b8c80-9711-11eb-9628-bf0a550b53a0.png">

- [ ] Fix size of Signup form

<hr>

### Keep the awesome work! 💪 Happy Coding for y'all!! 💻

**If you have any questions you can ask me on my Slack.**

**Best,**

**[💁‍♂️ Steven Jack Chung Yau](https://stevenchung.me)**

[LinkedIn](https://linkedin.com/in/stevenjchung) | [Twitter](https://twitter.com/_yiak) | [GitHub](https://github.com/jcy2704)

2021-04-07 09:00 UTC, igorkol91 commented
We fixed all the mandatory changes. Just want to point out that I checked the resolution and it looked fine on my monitor for 320 pixels.

2021-04-07 10:27 UTC, Berabjesus approved these changes
## **Status: PROJECT APPROVED** ✅ 
#### Excellent job on this project @igorkol91 and @ahzia . :fireworks: Keep it up.  :champagne: :champagne: 
**All the required changes by the previous TSE have been fulfilled in this project. It looks really good. I will go ahead and mark this as complete. 👍** 

### **Before you merge to the default branch please have a look at the following OPTIONAL comments below.**

- [ ] [optional] Your pull request title is too long. Make it brief from now on and use any discription of it in the description box which is currently empty.
#### your title 👇 
![image](https://user-images.githubusercontent.com/64360974/113851473-37b56e80-97a4-11eb-8b14-316e15d1238f.png)
#### your description  👇 
![image](https://user-images.githubusercontent.com/64360974/113851620-5ca9e180-97a4-11eb-994f-9baecaf7c92f.png)

- [ ] [optional] Even though you have not exhaustively done so, Don't repeat a CSS rule if it can be called from a bootstrap class. (Check comment below)


I wish you all the very best in your next tasks:1st_place_medal:
#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-04-07 10:27 UTC, Berabjesus commented on styles/main.css
> +  text-decoration: none;
- [ ] [OPTIONAL] use `text-decoration-none` of the bootstrap class instead of using css rule for it.

2021-04-07 10:27 UTC, Berabjesus commented on styles/main.css
> +  background-color: black;
- [ ] [OPTIONAL] use `bg-dark` of the bootstrap class instead of using css rule for it.

2021-04-07 13:03 UTC, merged